# Generated by Django 3.0.8 on 2020-07-30 18:45

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200730_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add your text', required=True))])), ('full_rich_text', streams.blocks.FullRichTextBlock()), ('simple_rich_text', streams.blocks.SimpleRichTextBlock())], blank=True, null=True),
        ),
    ]
